name: pocket_gpt
description: later

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  chat_gpt_flutter: ^1.0.8
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  easy_localization: ^3.0.1
  animated_bottom_navigation_bar: ^1.2.0
  animations: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true